services:
  php:
    build:
      context: ./docker/php
      args:
        ENABLE_XDEBUG: ${ENABLE_XDEBUG}
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    container_name: php-fpm

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    container_name: nginx

networks:
  app-network:
    driver: bridge